#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.1.1 on Fri Dec  5 23:19:18 2025
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class PersonalizaCombo(wx.Frame):
    def __init__(self, parent, informacion="",subtotal=0):
        # begin wxGlade: Dulceria.__init__
        super().__init__(parent, style= wx.DEFAULT_FRAME_STYLE)
        self.SetSize((666, 665))
        self.SetTitle("frame")

        self.panel_1 = wx.Panel(self, wx.ID_ANY)

        self.subtotalPersonalizaCombo = 0
        self.infoPersonalizaCombo = ""
        self.saborRefresco = ""
        self.cantidadSeleccionada = 0


        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1.Add(sizer_2, 1, wx.EXPAND, 0)

        bitmap_1 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("E:/CinePlusElizabeth3A/dulcerial.png", wx.BITMAP_TYPE_ANY))
        sizer_2.Add(bitmap_1, 0, 0, 0)

        label_1 = wx.StaticText(self.panel_1, wx.ID_ANY, "Personaliza Tu Combo")
        label_1.SetForegroundColour(wx.Colour(215, 0, 107))
        label_1.SetFont(wx.Font(14, wx.FONTFAMILY_DECORATIVE, wx.FONTSTYLE_ITALIC, wx.FONTWEIGHT_BOLD, 0, "Snap ITC"))
        sizer_2.Add(label_1, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 0)

        bitmap_2 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("E:/CinePlusElizabeth3A/dulcerial.png", wx.BITMAP_TYPE_ANY))
        sizer_2.Add(bitmap_2, 0, 0, 0)

        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1.Add(sizer_3, 1, wx.EXPAND, 0)

        bitmap_3 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./palomita.png", wx.BITMAP_TYPE_ANY))
        sizer_3.Add(bitmap_3, 0, 0, 0)

        sizer_4 = wx.BoxSizer(wx.VERTICAL)
        sizer_3.Add(sizer_4, 1, wx.EXPAND, 0)

        self.btnJumbo = wx.ToggleButton(self.panel_1, wx.ID_ANY, "Jumbo \n$100")
        self.btnJumbo.SetFont(wx.Font(10, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_ITALIC, wx.FONTWEIGHT_BOLD, 0, "Poor Richard"))
        sizer_4.Add(self.btnJumbo, 1, wx.ALIGN_CENTER_HORIZONTAL | wx.ALL, 0)

        self.spPalomitas = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        sizer_4.Add(self.spPalomitas, 1, wx.ALIGN_RIGHT | wx.ALL, 9)

        sizer_5 = wx.BoxSizer(wx.VERTICAL)
        sizer_3.Add(sizer_5, 1, wx.EXPAND, 0)

        self.btnGrande = wx.ToggleButton(self.panel_1, wx.ID_ANY, "Grande \n$80")
        self.btnGrande.SetFont(wx.Font(10, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_ITALIC, wx.FONTWEIGHT_BOLD, 0, "Poor Richard"))
        sizer_5.Add(self.btnGrande, 1, wx.ALIGN_CENTER_HORIZONTAL | wx.ALL, 14)

        sizer_6 = wx.BoxSizer(wx.VERTICAL)
        sizer_3.Add(sizer_6, 1, wx.EXPAND, 0)

        self.btnMediano = wx.ToggleButton(self.panel_1, wx.ID_ANY, "Mediano \n$50")
        self.btnMediano.SetFont(wx.Font(10, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_ITALIC, wx.FONTWEIGHT_BOLD, 0, "Poor Richard"))
        sizer_6.Add(self.btnMediano, 1, wx.ALIGN_CENTER_HORIZONTAL | wx.ALL, 14)

        sizer_7 = wx.BoxSizer(wx.VERTICAL)
        sizer_3.Add(sizer_7, 1, wx.EXPAND, 0)

        self.btnChico = wx.ToggleButton(self.panel_1, wx.ID_ANY, "Chico \n$35")
        self.btnChico.SetFont(wx.Font(10, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_ITALIC, wx.FONTWEIGHT_BOLD, 0, "Poor Richard"))
        sizer_7.Add(self.btnChico, 1, wx.ALIGN_CENTER_HORIZONTAL, 0)

        self.btnAgregar = wx.Button(self.panel_1, wx.ID_ANY, "Agregar")
        self.btnAgregar.SetFont(wx.Font(10, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_ITALIC, wx.FONTWEIGHT_BOLD, 0, "Poor Richard"))
        sizer_7.Add(self.btnAgregar, 1, wx.ALL, 0)

        sizer_8 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1.Add(sizer_8, 1, wx.EXPAND, 0)

        bitmap_4 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./refresco2.png", wx.BITMAP_TYPE_ANY))
        sizer_8.Add(bitmap_4, 0, 0, 0)

        sizer_9 = wx.BoxSizer(wx.VERTICAL)
        sizer_8.Add(sizer_9, 1, wx.EXPAND, 0)

        self.btnGrande2 = wx.ToggleButton(self.panel_1, wx.ID_ANY, "Grande \n$70")
        self.btnGrande2.SetFont(wx.Font(10, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_ITALIC, wx.FONTWEIGHT_BOLD, 0, "Poor Richard"))
        sizer_9.Add(self.btnGrande2, 0, 0, 0)

        self.cmbSabor = wx.ComboBox(self.panel_1, wx.ID_ANY, choices=[], style=wx.CB_DROPDOWN)
        sizer_9.Add(self.cmbSabor, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        sizer_10 = wx.BoxSizer(wx.VERTICAL)
        sizer_8.Add(sizer_10, 1, wx.EXPAND, 0)

        self.btnMediano2 = wx.ToggleButton(self.panel_1, wx.ID_ANY, "Mediano \n$60")
        self.btnMediano2.SetFont(wx.Font(10, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_ITALIC, wx.FONTWEIGHT_BOLD, 0, "Poor Richard"))
        sizer_10.Add(self.btnMediano2, 0, 0, 0)

        self.cmbCantidad = wx.ComboBox(self.panel_1, wx.ID_ANY, choices=[], style=wx.CB_DROPDOWN)
        sizer_10.Add(self.cmbCantidad, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        sizer_11 = wx.BoxSizer(wx.VERTICAL)
        sizer_8.Add(sizer_11, 1, wx.EXPAND, 0)

        self.btnChico2 = wx.ToggleButton(self.panel_1, wx.ID_ANY, "Chico \n$50")
        self.btnChico2.SetFont(wx.Font(10, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_ITALIC, wx.FONTWEIGHT_BOLD, 0, "Poor Richard"))
        sizer_11.Add(self.btnChico2, 0, 0, 0)

        self.btnAgregar2 = wx.Button(self.panel_1, wx.ID_ANY, "Agregar")
        self.btnAgregar2.SetFont(wx.Font(10, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_ITALIC, wx.FONTWEIGHT_BOLD, 0, "Poor Richard"))
        sizer_11.Add(self.btnAgregar2, 1, wx.ALIGN_CENTER_HORIZONTAL | wx.ALL, 0)

        sizer_12 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1.Add(sizer_12, 1, wx.EXPAND, 0)

        bitmap_5 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./nachos.png", wx.BITMAP_TYPE_ANY))
        sizer_12.Add(bitmap_5, 0, 0, 0)

        self.btnGrande3 = wx.ToggleButton(self.panel_1, wx.ID_ANY, "Grande \n$60")
        self.btnGrande3.SetFont(wx.Font(10, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_ITALIC, wx.FONTWEIGHT_BOLD, 0, "Poor Richard"))
        sizer_12.Add(self.btnGrande3, 0, 0, 0)

        sizer_13 = wx.BoxSizer(wx.VERTICAL)
        sizer_12.Add(sizer_13, 1, wx.EXPAND, 0)

        self.btnMediano3 = wx.ToggleButton(self.panel_1, wx.ID_ANY, "Mediano\n$40")
        self.btnMediano3.SetFont(wx.Font(10, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_ITALIC, wx.FONTWEIGHT_BOLD, 0, "Poor Richard"))
        sizer_13.Add(self.btnMediano3, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        self.spNachos = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        sizer_13.Add(self.spNachos, 0, 0, 0)

        sizer_14 = wx.BoxSizer(wx.VERTICAL)
        sizer_12.Add(sizer_14, 1, wx.EXPAND, 0)

        self.btnChico3 = wx.ToggleButton(self.panel_1, wx.ID_ANY, "Chico\n$25")
        self.btnChico3.SetFont(wx.Font(10, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_ITALIC, wx.FONTWEIGHT_BOLD, 0, "Poor Richard"))
        sizer_14.Add(self.btnChico3, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        self.btnAgregar3 = wx.Button(self.panel_1, wx.ID_ANY, "Agregar")
        self.btnAgregar3.SetFont(wx.Font(10, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_ITALIC, wx.FONTWEIGHT_BOLD, 0, "Poor Richard"))
        sizer_14.Add(self.btnAgregar3, 0, 0, 0)

        sizer_15 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1.Add(sizer_15, 1, wx.EXPAND, 0)

        bitmap_6 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./icees.png", wx.BITMAP_TYPE_ANY))
        sizer_15.Add(bitmap_6, 0, 0, 0)

        sizer_16 = wx.BoxSizer(wx.VERTICAL)
        sizer_15.Add(sizer_16, 1, wx.EXPAND, 0)

        self.btnJumbo2 = wx.ToggleButton(self.panel_1, wx.ID_ANY, "Jumbo\n$100")
        self.btnJumbo2.SetFont(wx.Font(10, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_ITALIC, wx.FONTWEIGHT_BOLD, 0, "Poor Richard"))
        sizer_16.Add(self.btnJumbo2, 0, 0, 0)

        self.cmbSaborIcee = wx.ComboBox(self.panel_1, wx.ID_ANY, choices=[], style=wx.CB_DROPDOWN)
        sizer_16.Add(self.cmbSaborIcee, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        self.btnGrande4 = wx.ToggleButton(self.panel_1, wx.ID_ANY, "Grande \n$80")
        self.btnGrande4.SetFont(wx.Font(10, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_ITALIC, wx.FONTWEIGHT_BOLD, 0, "Poor Richard"))
        sizer_15.Add(self.btnGrande4, 0, 0, 0)

        self.btnMediano4 = wx.ToggleButton(self.panel_1, wx.ID_ANY, "Mediano\n$50")
        self.btnMediano4.SetFont(wx.Font(10, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_ITALIC, wx.FONTWEIGHT_BOLD, 0, "Poor Richard"))
        sizer_15.Add(self.btnMediano4, 0, 0, 0)

        sizer_17 = wx.BoxSizer(wx.VERTICAL)
        sizer_15.Add(sizer_17, 1, wx.EXPAND, 0)

        self.btnChico4 = wx.ToggleButton(self.panel_1, wx.ID_ANY, "Chico\n$35")
        self.btnChico4.SetFont(wx.Font(10, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_ITALIC, wx.FONTWEIGHT_BOLD, 0, "Poor Richard"))
        sizer_17.Add(self.btnChico4, 0, 0, 0)

        self.btnAgregar4 = wx.Button(self.panel_1, wx.ID_ANY, "Agregar")
        self.btnAgregar4.SetFont(wx.Font(10, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_ITALIC, wx.FONTWEIGHT_BOLD, 0, "Poor Richard"))
        sizer_17.Add(self.btnAgregar4, 0, 0, 0)

        sizer_21 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1.Add(sizer_21, 1, wx.EXPAND, 0)

        self.lbProductosAgregados = wx.StaticText(self.panel_1, wx.ID_ANY, "Productos Agregados: ---")
        self.lbProductosAgregados.SetFont(wx.Font(11, wx.FONTFAMILY_DECORATIVE, wx.FONTSTYLE_ITALIC, wx.FONTWEIGHT_BOLD, 0, "Snap ITC"))
        sizer_21.Add(self.lbProductosAgregados, 0, 0, 0)

        self.lbSubtotal = wx.StaticText(self.panel_1, wx.ID_ANY, "Subtotal: ---")
        self.lbSubtotal.SetFont(wx.Font(11, wx.FONTFAMILY_DECORATIVE, wx.FONTSTYLE_ITALIC, wx.FONTWEIGHT_BOLD, 0, "Snap ITC"))
        sizer_21.Add(self.lbSubtotal, 0, wx.ALL, 0)

        sizer_18 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1.Add(sizer_18, 1, wx.EXPAND, 0)

        self.btnCrear = wx.ToggleButton(self.panel_1, wx.ID_ANY, "Crear combo")
        self.btnCrear.SetMinSize((215, 23))
        self.btnCrear.SetFont(wx.Font(12, wx.FONTFAMILY_DECORATIVE, wx.FONTSTYLE_ITALIC, wx.FONTWEIGHT_BOLD, 0, "Showcard Gothic"))
        sizer_18.Add(self.btnCrear, 1, wx.ALIGN_CENTER_VERTICAL, 0)

        self.btnIndividual = wx.ToggleButton(self.panel_1, wx.ID_ANY, "Agregar producto individual")
        self.btnIndividual.SetFont(wx.Font(12, wx.FONTFAMILY_DECORATIVE, wx.FONTSTYLE_ITALIC, wx.FONTWEIGHT_BOLD, 0, "Showcard Gothic"))
        sizer_18.Add(self.btnIndividual, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 0)

        self.btnSiguiente = wx.Button(self.panel_1, wx.ID_ANY, "Siguiente")
        self.btnSiguiente.SetFont(wx.Font(12, wx.FONTFAMILY_DECORATIVE, wx.FONTSTYLE_ITALIC, wx.FONTWEIGHT_BOLD, 0, "Showcard Gothic"))
        sizer_18.Add(self.btnSiguiente, 1, wx.ALIGN_CENTER_VERTICAL, 0)

        sizer_19 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1.Add(sizer_19, 1, wx.EXPAND, 0)

        self.btnAtras = wx.Button(self.panel_1, wx.ID_ANY, "Atras")
        self.btnAtras.SetFont(wx.Font(12, wx.FONTFAMILY_DECORATIVE, wx.FONTSTYLE_ITALIC, wx.FONTWEIGHT_BOLD, 0, "Showcard Gothic"))
        sizer_19.Add(self.btnAtras, 1, wx.ALIGN_CENTER_VERTICAL, 0)

        self.btnCompra = wx.Button(self.panel_1, wx.ID_ANY, "Compra")
        self.btnCompra.SetFont(wx.Font(12, wx.FONTFAMILY_DECORATIVE, wx.FONTSTYLE_ITALIC, wx.FONTWEIGHT_BOLD, 0, "Showcard Gothic"))
        sizer_19.Add(self.btnCompra, 1, wx.ALIGN_CENTER_VERTICAL, 0)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()

        self.spPalomitas.Bind(wx.EVT_SPINCTRL, self.calcularPalomitas)
        self.btnAgregar.Bind(wx.EVT_BUTTON, self.agregarPalomitas)
        self.cmbSabor.Bind(wx.EVT_COMBOBOX, self.seleccionRefrescoSabor)
        self.cmbCantidad.Bind(wx.EVT_COMBOBOX, self.SeleccionCantidad)
        self.btnAgregar2.Bind(wx.EVT_BUTTON, self.agregarRefresco)
        self.spNachos.Bind(wx.EVT_SPINCTRL, self.calvcularNachos)
        self.btnAgregar3.Bind(wx.EVT_BUTTON, self.agregarNachos)
        self.cmbSaborIcee.Bind(wx.EVT_COMBOBOX, self.seleccionSaborIcee)
        self.btnAgregar4.Bind(wx.EVT_BUTTON, self.agregarIcee)
        self.btnSiguiente.Bind(wx.EVT_BUTTON, self.siguientePersonaliza)
        self.btnAtras.Bind(wx.EVT_BUTTON, self.limpiarPersonaliza)
        self.btnCompra.Bind(wx.EVT_BUTTON, self.compraPersonaliza)
        # end wxGlade

    def calcularPalomitas(self, event):  # wxGlade: PersonalizaCombo.<event_handler>
        cantidad = int(self.spPalomitas.GetValue())
        tamaño = self.spPalomitas.GetStringSelection()
        preciosPalomitas = {
            "Jumbo": 100,
            "Grande": 80,
            "Mediano": 50,
            "Chico": 35
        }
        precio = preciosPalomitas.get(tamaño, 35)  # default Chico si no selecciona
        subtotal = cantidad * precio
        self.subtotalPersonalizaCombo += subtotal
        self.lbSubtotal.SetLabel(f"${self.subtotalPersonalizaCombo}")
        self.infoPersonalizaCombo += f"{cantidad} Palomitas {tamaño} (${subtotal})\n"
        self.lbProductosAgregados.SetLabel(self.infoPersonalizaCombo)
        event.Skip()

    def agregarPalomitas(self, event):  # wxGlade: PersonalizaCombo.<event_handler>
        numero = int(self.spPalomitas.GetValue())
        tamaño = self.cmbCantidad.GetStringSelection()
        if tamaño == "Jumbo":
            precio = 100
        elif tamaño == "Grande":
            precio = 80
        elif tamaño == "Mediano":
            precio = 50
        elif tamaño == "Chico":
            precio = 35
        else:
            precio = 35

        subtotal = numero * precio
        self.subtotalPersonalizaCombo += subtotal
        self.lbSubtotal.SetLabel(f"${self.subtotalPersonalizaCombo}")
        self.infoPersonalizaCombo += f"{numero} Palomitas {tamaño} (${precio})\n"
        self.lbProductosAgregados.SetLabel(self.infoPersonalizaCombo)
        event.Skip()

    def seleccionRefrescoSabor(self, event):  # wxGlade: PersonalizaCombo.<event_handler>
        self.cmbSabor.SetItems(["Coca-Cola", "Manzanita", "Sprite"])
        self.saborRefresco = self.cmbSabor.GetStringSelection()
        print(f"Sabor de refresco seleccionado: {self.saborRefresco}")        
        event.Skip()

    def SeleccionCantidad(self, event):  # wxGlade: PersonalizaCombo.<event_handler>
        print("Event handler 'SeleccionCantidad' not implemented!")
        event.Skip()

    def agregarRefresco(self, event):  # wxGlade: PersonalizaCombo.<event_handler>
        tamaño = self.cmbSabor.GetStringSelection()
        sabor = self.cmbSabor.GetStringSelection()
        if tamaño == "Grande":
            precio = 70
        elif tamaño == "Mediano":
            precio = 60
        elif tamaño == "Chico":
            precio = 50
        else:
            precio = 50

        subtotal = precio
        self.subtotalPersonalizaCombo += subtotal
        self.lbSubtotal.SetLabel(f"${self.subtotalPersonalizaCombo}")
        self.infoPersonalizaCombo += f"1 Refresco {tamaño} {sabor} (${precio})\n"
        self.lbProductosAgregados.SetLabel(self.infoPersonalizaCombo)
        event.Skip()

    def calvcularNachos(self, event):  # wxGlade: PersonalizaCombo.<event_handler>
        cantidad = int(self.spNachos.GetValue())
        tamaño = self.cmbCantidad.GetStringSelection()

        preciosNachos = {
            "Grande": 60,
            "Mediano": 40,
            "Chico": 25
        }
        precio = preciosNachos.get(tamaño, 40)  # default mediano
        subtotal = cantidad * precio
        self.subtotalPersonalizaCombo += subtotal
        self.lbSubtotal.SetLabel(f"${self.subtotalPersonalizaCombo}")
        self.infoPersonalizaCombo += f"{cantidad} Nachos {tamaño} (${subtotal})\n"
        self.lbProductosAgregados.SetLabel(self.infoPersonalizaCombo)
        event.Skip()

    def agregarNachos(self, event):  # wxGlade: PersonalizaCombo.<event_handler>
        numero = int(self.spNachos.GetValue())
        tamaño = self.cmbCantidad.GetStringSelection()
        if tamaño == "Grande":
            precio = 60
        elif tamaño == "Mediano":
            precio = 40
        elif tamaño == "Chico":
            precio = 25
        else:
            precio = 25

        subtotal = numero * precio
        self.subtotalPersonalizaCombo += subtotal
        self.lbSubtotal.SetLabel(f"${self.subtotalPersonalizaCombo}")
        self.infoPersonalizaCombo += f"{numero} Nachos {tamaño} (${precio})\n"
        self.lbProductosAgregados.SetLabel(self.infoPersonalizaCombo)
        event.Skip()

    def seleccionSaborIcee(self, event):  # wxGlade: PersonalizaCombo.<event_handler>
        tamaño = self.cmbSaborIcee.GetStringSelection()
        sabor = self.cmbSaborIcee    
        event.Skip()

    def agregarIcee(self, event):  # wxGlade: PersonalizaCombo.<event_handler>
        tamaño = self.cmbSaborIcee.GetStringSelection()
        sabor = self.cmbSaborIcee.GetStringSelection()
        if tamaño == "Jumbo":
            precio = 100
        elif tamaño == "Grande":
            precio = 80
        elif tamaño == "Mediano":
            precio = 50
        elif tamaño == "Chico":
            precio = 35
        else:
            precio = 35

        subtotal = precio
        self.subtotalPersonalizaCombo += subtotal
        self.lbSubtotal.SetLabel(f"${self.subtotalPersonalizaCombo}")
        self.infoPersonalizaCombo += f"1 ICEE {tamaño} {sabor} (${precio})\n"
        self.lbProductosAgregados.SetLabel(self.infoPersonalizaCombo)
        event.Skip()

    def siguientePersonaliza(self, event):  # wxGlade: PersonalizaCombo.<event_handler>
        #v5.Show()
        #self.Close()")
        event.Skip()

    def limpiarPersonaliza(self, event):  # wxGlade: PersonalizaCombo.<event_handler>
        self.subtotalPersonalizaCombo = 0
        self.infoPersonalizaCombo = ""
        self.lbSubtotal.SetLabel("$0")
        self.lbProductosAgregados.SetLabel("")
        self.spNachos.SetValue(0)
        try:
            self.cmbCantidad.SetSelection(0)  # Elige el primer tamaño
        except:
            pass
        event.Skip()

    def compraPersonaliza(self, event):  # wxGlade: PersonalizaCombo.<event_handler>
        self.informacion=""
        pregunta=wx.MessageDialog(
            self,
            f"Gracias por su compra, vuelva pronto!! :)\n"
            f" ¿Esta satisfecho con su compra?\n\n{self.informacion}\n"
            "Personaliza Combo",
            style=wx.YES_NO|wx.ICON_QUESTION
        )

        respuesta=pregunta.ShowModal()
        pregunta.Destroy
        if respuesta==wx.ID_YES:
            print("Venta Finalizada!!!")
            self.Hide()
            event.Skip()
# end of class PersonalizaCombo

class MyApp(wx.App):
    def OnInit(self):
        self.frame = PersonalizaCombo(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True

# end of class MyApp

if __name__ == "__main__":
    app = MyApp(0)
    app.MainLoop()
