#!/usr/bin/env python3
# -*- coding: CP1252 -*-
#
# generated by wxGlade 1.1.1 on Thu Dec  4 13:10:26 2025
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class ventana3(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: ventana3.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((391, 602))
        self.SetTitle("frame_2")

        self.panel_1 = wx.Panel(self, wx.ID_ANY)
        self.panel_1.SetBackgroundColour(wx.Colour(255, 167, 79))

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        grid_sizer_1 = wx.GridSizer(1, 3, 0, 0)
        sizer_1.Add(grid_sizer_1, 1, wx.EXPAND, 0)

        bitmap_1 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./taquilla.jpg", wx.BITMAP_TYPE_ANY))
        grid_sizer_1.Add(bitmap_1, 0, 0, 0)

        label_1 = wx.StaticText(self.panel_1, wx.ID_ANY, "Registro\n de boletos\n", style=wx.ALIGN_CENTER_HORIZONTAL)
        label_1.SetMinSize((100, 60))
        label_1.SetFont(wx.Font(14, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Yu Gothic UI"))
        grid_sizer_1.Add(label_1, 0, wx.ALIGN_CENTER, 0)

        bitmap_2 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./taquilla.jpg", wx.BITMAP_TYPE_ANY))
        grid_sizer_1.Add(bitmap_2, 0, wx.ALIGN_RIGHT, 0)

        grid_sizer_2 = wx.GridSizer(1, 3, 0, 0)
        sizer_1.Add(grid_sizer_2, 1, wx.EXPAND, 0)

        label_5 = wx.StaticText(self.panel_1, wx.ID_ANY, "Pelicula:")
        label_5.SetFont(wx.Font(10, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Yu Gothic UI"))
        grid_sizer_2.Add(label_5, 0, 0, 0)

        self.cmbPelicula = wx.ComboBox(self.panel_1, wx.ID_ANY, choices=["Conjuro4","Rio","Yo antes de ti",], style=wx.CB_DROPDOWN)
        self.cmbPelicula.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Yu Gothic UI"))
        grid_sizer_2.Add(self.cmbPelicula, 0, wx.ALIGN_CENTER, 0)

        self.bmPelicula = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./pelicula1.jpg", wx.BITMAP_TYPE_ANY))
        grid_sizer_2.Add(self.bmPelicula, 0, 0, 0)

        grid_sizer_5 = wx.GridSizer(1, 2, 0, 0)
        sizer_1.Add(grid_sizer_5, 1, wx.EXPAND, 0)

        label_6 = wx.StaticText(self.panel_1, wx.ID_ANY, "Sala:")
        label_6.SetFont(wx.Font(10, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Yu Gothic UI"))
        grid_sizer_5.Add(label_6, 0, 0, 0)

        self.lbSala = wx.StaticText(self.panel_1, wx.ID_ANY, "...")
        self.lbSala.SetFont(wx.Font(10, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        grid_sizer_5.Add(self.lbSala, 0, 0, 0)

        grid_sizer_3 = wx.GridSizer(1, 4, 0, 0)
        sizer_1.Add(grid_sizer_3, 1, wx.EXPAND, 0)

        label_8 = wx.StaticText(self.panel_1, wx.ID_ANY, "Horario")
        label_8.SetFont(wx.Font(10, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Yu Gothic UI"))
        grid_sizer_3.Add(label_8, 0, 0, 0)

        self.rbHorario1 = wx.RadioButton(self.panel_1, wx.ID_ANY, "00:00")
        self.rbHorario1.SetFont(wx.Font(10, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Yu Gothic UI"))
        grid_sizer_3.Add(self.rbHorario1, 0, 0, 0)

        self.rbHorario2 = wx.RadioButton(self.panel_1, wx.ID_ANY, "00:00")
        self.rbHorario2.SetFont(wx.Font(10, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Yu Gothic UI"))
        grid_sizer_3.Add(self.rbHorario2, 0, 0, 0)

        self.rbHorario3 = wx.RadioButton(self.panel_1, wx.ID_ANY, "00:00")
        self.rbHorario3.SetFont(wx.Font(10, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Yu Gothic UI"))
        grid_sizer_3.Add(self.rbHorario3, 0, 0, 0)

        grid_sizer_4 = wx.GridSizer(2, 1, 0, 0)
        sizer_1.Add(grid_sizer_4, 1, wx.EXPAND, 0)

        label_2 = wx.StaticText(self.panel_1, wx.ID_ANY, "Cantidad de Boletos", style=wx.ALIGN_CENTER_HORIZONTAL)
        label_2.SetMinSize((150, 30))
        label_2.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Yu Gothic UI"))
        grid_sizer_4.Add(label_2, 0, wx.ALIGN_CENTER, 0)

        grid_sizer_6 = wx.GridSizer(2, 2, 0, 0)
        grid_sizer_4.Add(grid_sizer_6, 1, wx.EXPAND, 0)

        label_3 = wx.StaticText(self.panel_1, wx.ID_ANY, "Adultos($50):", style=wx.ALIGN_CENTER_HORIZONTAL)
        label_3.SetMinSize((77, 18))
        label_3.SetFont(wx.Font(10, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Yu Gothic UI"))
        grid_sizer_6.Add(label_3, 0, wx.ALIGN_CENTER, 0)

        self.tfAdultos = wx.TextCtrl(self.panel_1, wx.ID_ANY, "", style=wx.TE_PROCESS_ENTER)
        self.tfAdultos.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Yu Gothic UI"))
        grid_sizer_6.Add(self.tfAdultos, 0, wx.ALIGN_CENTER, 0)

        label_4 = wx.StaticText(self.panel_1, wx.ID_ANY, "Menores($35):", style=wx.ALIGN_CENTER_HORIZONTAL)
        label_4.SetMinSize((90, 18))
        label_4.SetFont(wx.Font(10, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Yu Gothic UI"))
        grid_sizer_6.Add(label_4, 0, wx.ALIGN_CENTER, 0)

        self.tfMenores = wx.TextCtrl(self.panel_1, wx.ID_ANY, "", style=wx.TE_PROCESS_ENTER)
        self.tfMenores.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Yu Gothic UI"))
        grid_sizer_6.Add(self.tfMenores, 0, wx.ALIGN_CENTER, 0)

        self.lbSubtotal = wx.StaticText(self.panel_1, wx.ID_ANY, "Subtotal:$")
        self.lbSubtotal.SetFont(wx.Font(10, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Yu Gothic UI"))
        sizer_1.Add(self.lbSubtotal, 0, 0, 0)

        grid_sizer_7 = wx.GridSizer(1, 2, 0, 0)
        sizer_1.Add(grid_sizer_7, 1, wx.EXPAND, 0)

        self.btnLimpiar = wx.Button(self.panel_1, wx.ID_ANY, "atras")
        self.btnLimpiar.SetBackgroundColour(wx.Colour(252, 130, 62))
        self.btnLimpiar.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Yu Gothic UI"))
        grid_sizer_7.Add(self.btnLimpiar, 0, wx.ALIGN_CENTER, 0)

        self.btnSiguiente = wx.Button(self.panel_1, wx.ID_ANY, "confirmar")
        self.btnSiguiente.SetBackgroundColour(wx.Colour(252, 130, 62))
        self.btnSiguiente.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Yu Gothic UI"))
        grid_sizer_7.Add(self.btnSiguiente, 0, wx.ALIGN_CENTER, 0)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()

        self.cmbPelicula.Bind(wx.EVT_COMBOBOX, self.seleccionPelicula)
        self.rbHorario1.Bind(wx.EVT_RADIOBUTTON, self.seleccionHorario1)
        self.rbHorario2.Bind(wx.EVT_RADIOBUTTON, self.seleccionHorario2)
        self.rbHorario3.Bind(wx.EVT_RADIOBUTTON, self.seleccionHorario3)
        self.tfAdultos.Bind(wx.EVT_TEXT_ENTER, self.sumarAdultos)
        self.tfMenores.Bind(wx.EVT_TEXT_ENTER, self.sumarMenores)
        self.btnLimpiar.Bind(wx.EVT_BUTTON, self.limpiarTaquilla)
        self.btnSiguiente.Bind(wx.EVT_BUTTON, self.siguienteVentana)
        # end wxGlade

    def cargar_imagen(self,ruta):
        print(f"Imagen a cargar: {ruta}")
        bitmap =wx.Bitmap(ruta, wx.BITMAP_TYPE_ANY)
        self.bmPelicula.SetBitmap(bitmap)
        
    def seleccionPelicula(self, event):  # wxGlade: Ventana2.<event_handler>
        pelicula=self.cmbPelicula.GetValue()
        imagen=""
        sala=""
        horario1=horario2=horario3=""
        
        print(f"Pelicula seleccionada: {pelicula}")
        
        if pelicula == "Conjuro4":
            imagen="peliula1.jpg"
            sala="2"
            horario1="8:00"
            horario2="10:00"
            horario3="12:00"

        elif pelicula == "Rio":
            imagen="pelicula2.jpg"
            sala="5"
            horario1="01:30"
            horario2="03:30"
            horario3="05:30"

        elif pelicula == "Yo antes de ti":
            imagen="pelicula3.jpg"
            sala="9"
            horario1="07:00"
            horario2="09:00"
            horario3="10:00"
        
        self.cargar_imagen(imagen)
        self.lbSala.SetLabel(sala)
        self.rbHorario1.SetLabel(horario1)
        self.rbHorario2.SetLabel(horario2)
        self.rbHorario3.SetLabel(horario3)
        self.informacion=f"Pelicula: {pelicula}  \n  Sala: {sala}"
        print(f"Listo para disfrutar de \n {self.informacion}")
        event.Skip()

    
        

    def seleccionHorario1(self, event):  # wxGlade: Ventana2.<event_handler>
        self.horarioSeleccionado=self.rbHorario1.GetLabelText()
        event.Skip()

    def seleccionHorario2(self, event):  # wxGlade: Ventana2.<event_handler>
        self.horarioSeleccionado=self.rbHorario2.GetLabelText()
        event.Skip()

    def seleccionHorario3(self, event):  # wxGlade: Ventana2.<event_handler>
        self.horarioSeleccionado=self.rbHorario3.GetLabelText()
        event.Skip()

    def sumarAdultos(self, event):  # wxGlade: Ventana2.<event_handler>
        try:
            self.adultos = int(self.tfAdultos.GetValue())
            subtotal_a = self.adultos * 80
            self.subtotal=subtotal_a 
            self.lbSubtotal.SetLabel(f"Subtotal: ${subtotal_a:.2f}")
        except ValueError:
            wx.MessageBox("Por favor ingresa un número válido", "Error", wx.OK | wx.ICON_ERROR)
        event.Skip()

    def sumarMenores(self, event):  # wxGlade: Ventana2.<event_handler>
        try:
            self.menores = int(self.tfMenores.GetValue())
            subtotal_b = self.menores * 70
            self.subtotal=(self.adultos*80) + subtotal_b 
            self.lbSubtotal.SetLabel(f"Subtotal: ${self.subtotal:.2f}")
        except ValueError:
            wx.MessageBox("Por favor ingresa un número válido", "Error", wx.OK | wx.ICON_ERROR)
        event.Skip()

    #Creacion de la función limpiar para la Ventana 2   
    def limpiarValores_Campos(self):

        #Limpiar Variables de Instancia
        self.subtotal=0
        self.adultos=0
        self.menores=0
        self.informacion=""
        self.horarioSeleccionado=""

        #Limpiar Campos
        self.cargar_imagen("logo.png")
        self.rbHorario1.SetLabel("00:00")
        self.rbHorario2.SetLabel("00:00")
        self.rbHorario3.SetLabel("00:00")
        self.rbHorario1.SetValue(False)
        self.rbHorario2.SetValue(False)
        self.rbHorario3.SetValue(False)
        self.cmbPelicula.SetSelection(wx.NOT_FOUND)
        self.lbSala.SetLabel("---")
        self.tfAdultos.SetValue("0")
        self.tfMenores.SetValue("0")
        self.lbSubtotal.SetLabel("0")
        


    def limpiarTaquilla(self, event):  # wxGlade: Ventana2.<event_handler>
        self.limpiarValores_Campos()
        event.Skip()

    def siguienteVentana(self, event):  # wxGlade: Ventana2.<event_handler>
        self.informacion = f"{self.informacion}  \n  Horario: {self.horarioSeleccionado}"
        self.informacion = f"{self.informacion}  \n  Adultos: {self.adultos}\n  Menores de 12 años: {self.menores}"
        self.informacion = f"{self.informacion}  \n  Subtotal: {self.subtotal}"
        
        pregunta = wx.MessageDialog(
        self,
        f"Confirmacion de Registro de boletos.\n"
        f"¿Esta seguro que desea adquirir?\n\n{self.informacion}",
        "registro de boletos",
        style=wx.YES_NO | wx.ICON_QUESTION
        )
        
        respuesta = pregunta.ShowModal()
        pregunta.Destroy()  # Cerramos el diálogo
        
        if respuesta == wx.ID_YES:
            print(f"registro de voletos realizado \n {self.informacion}")
            #v4 = Ventana3(self, informacion=self.informacion, subtotal=self.subtotal)
            #v4.Show()
            self.limpiarValores_Campos()
            self.Hide()
        elif respuesta == wx.ID_NO:
            self.limpiarValores_Campos()

        event.Skip()
    
# end of class ventana3

class MyAppCinePlus(wx.App):
    def OnInit(self):
        self.frame_4 = ventana3(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame_4)
        self.frame_4.Show()
        return True

# end of class MyAppCinePlus

if __name__ == "__main__":
    appCinePlus = MyAppCinePlus(0)
    appCinePlus.MainLoop()
